apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardened
spec:
  selector:
    matchLabels:
      app: hardened
  template:
    metadata:
      labels:
        app: hardened
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: hardened
        image: nginx:1.23.3
        securityContext:
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10002
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: 
              - ALL
        env:
          - name: NGINX_HOST
            value: "0.0.0.0"
          - name: NGINX_PORT
            value: "8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "90Mi"
            cpu: "200m"
        volumeMounts:
          - mountPath: /var/cache/nginx/client_temp
            name: client-temp-dir
          - mountPath: /var/cache/nginx/proxy_temp
            name: proxy-temp-dir
          - mountPath: /var/cache/nginx/fastcgi_temp
            name: fastcgi-temp-dir
          - mountPath: /var/cache/nginx/uwsgi_temp
            name: uwsgi-temp-dir
          - mountPath: /var/cache/nginx/scgi_temp
            name: scgi-temp-dir
          - mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            name: nginx-config
          - mountPath: /data/www/index.html
            subPath: index.html
            name: nginx-config
          - mountPath: /var/run
            name: pid
        ports:
        - containerPort: 8080
      volumes:
        - name: client-temp-dir
          emptyDir: {}
        - name: proxy-temp-dir
          emptyDir: {}
        - name: fastcgi-temp-dir
          emptyDir: {}
        - name: uwsgi-temp-dir
          emptyDir: {}
        - name: scgi-temp-dir
          emptyDir: {}
        - name: pid
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    http {
        server {
            listen 8080;
            location / {
                root /data/www;
            }
        }
    }
    events {
    }
  index.html: |-
    <h1>It's working!</h1>